[relaychain]
default_command = "polkadot"
chain = "dev"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
ws_port = 9999

[[parachains]]
id = 2000 #needs to be non 1000 because 1000 is asset hub that does not support reserve transfers


[parachains.collator]
name = "alice"
ws_port = 9988
command = "parachain-template-node"
